# 服务端口号
server:
  port: 38002
spring:
  application:
    # 服务应用名
    name: estore-service-order
  # MySQL数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/estore_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    # nacos注册中心
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    # 配置Sentinel流量控制组件
    sentinel:
      transport:
        # http服务的端口 用于规则设置生效时使用
        port: 8719
        # sentinel控制台服务端的地址
        dashboard: http://localhost:8080
  # redis配置
  redis:
    host: localhost
    port: 6379
# openfeign配置
feign:
  client:
    config:
      default: # default指定的是所有的 被调用方  都设置为该配置超时时间，可以设置为某一个微服务对应的服务名
        connectionTimeout: 5000 # 连接超时时间
        readTimeout: 5000 # 读取超时时间
  # 启用okhttp
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  # 开启feign对sentinel的支持 实现feign接口异常回调容错
  sentinel:
    enabled: true
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 配置控制台打印带参数sql执行语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  # 如果为true则开启生产环境屏蔽
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: 123